/**
 * Generates src/data/stationLocations.ts from a MARTA GTFS stops.txt.
 *
 * Usage:
 *   npm run seed:gtfs -- path/to/stops.txt
 *
 * The GTFS static feed comes from https://itsmarta.com/google_transit_feed/google_transit.zip
 * (no API key). Download and unzip it locally; don't commit the feed itself.
 *
 * Matching: GTFS parent stations (location_type=1) named "* STATION" are
 * normalized and matched against station ids in src/data/stations.ts.
 * Anything normalization can't match must get an entry in station-aliases.ts.
 * The script exits non-zero if any station id is unmatched or any alias is
 * unused, so drift in a future GTFS feed surfaces immediately.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { parse } from "csv-parse/sync";
import { stations } from "../../src/data/stations";
import { stationAliases } from "./station-aliases";

type GtfsStop = {
  stop_id: string;
  stop_name: string;
  stop_lat: string;
  stop_lon: string;
  location_type: string;
};

function normalizeGtfsName(name: string): string {
  return name
    .toUpperCase()
    .replace(/\bSTATION\b/g, " ")
    .replace(/[^A-Z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();
}

const stopsPath = process.argv[2];
if (!stopsPath) {
  console.error("Usage: npm run seed:gtfs -- path/to/stops.txt");
  process.exit(1);
}

const rows: GtfsStop[] = parse(readFileSync(stopsPath, "utf8"), {
  columns: true,
  skip_empty_lines: true,
});

const parentStations = rows.filter(
  (r) => r.location_type === "1" && / STATION$/.test(r.stop_name.trim()),
);
console.log(
  `${rows.length} GTFS stops, ${parentStations.length} rail parent stations`,
);

const byNormalizedName = new Map<string, GtfsStop>();
const byExactName = new Map<string, GtfsStop>();
for (const stop of parentStations) {
  const name = stop.stop_name.trim();
  byExactName.set(name, stop);
  const normalized = normalizeGtfsName(name);
  if (byNormalizedName.has(normalized)) {
    console.error(`Duplicate normalized GTFS name: ${normalized}`);
    process.exit(1);
  }
  byNormalizedName.set(normalized, stop);
}

const matched = new Map<string, GtfsStop>();
const unmatched: string[] = [];
const usedAliases = new Set<string>();

for (const station of stations) {
  const alias = stationAliases[station.id];
  let stop: GtfsStop | undefined;
  if (alias) {
    stop = byExactName.get(alias);
    if (stop) usedAliases.add(station.id);
    else console.error(`Alias for "${station.id}" matches no GTFS stop: "${alias}"`);
  } else {
    stop = byNormalizedName.get(station.id);
  }
  if (stop) matched.set(station.id, stop);
  else unmatched.push(station.id);
}

const unusedAliases = Object.keys(stationAliases).filter(
  (id) => !usedAliases.has(id),
);

if (unmatched.length > 0 || unusedAliases.length > 0) {
  if (unmatched.length > 0)
    console.error(`Unmatched station ids: ${unmatched.join(", ")}`);
  if (unusedAliases.length > 0)
    console.error(`Unused aliases: ${unusedAliases.join(", ")}`);
  process.exit(1);
}

const matchedStopIds = new Set(
  [...matched.values()].map((s) => s.stop_id),
);
const leftoverGtfs = parentStations.filter((s) => !matchedStopIds.has(s.stop_id));
if (leftoverGtfs.length > 0) {
  console.warn(
    `Note: ${leftoverGtfs.length} GTFS rail stations not in stations.ts: ${leftoverGtfs
      .map((s) => s.stop_name)
      .join(", ")}`,
  );
}

const entries = stations
  .map((station) => {
    const stop = matched.get(station.id)!;
    return `  "${station.id}": { lat: ${Number(stop.stop_lat)}, lng: ${Number(
      stop.stop_lon,
    )}, gtfsStopId: "${stop.stop_id}", gtfsStopName: "${stop.stop_name.trim()}" },`;
  })
  .join("\n");

const output = `// GENERATED by scripts/seed/ingest-gtfs.ts — do not edit by hand.
// Source: MARTA GTFS static feed (stops.txt), parent rail stations.
// Regenerate with: npm run seed:gtfs -- path/to/stops.txt

export type StationLocation = {
  lat: number;
  lng: number;
  gtfsStopId: string;
  gtfsStopName: string;
};

export const stationLocations: Record<string, StationLocation> = {
${entries}
};
`;

writeFileSync("src/data/stationLocations.ts", output);
console.log(
  `${matched.size}/${stations.length} matched — wrote src/data/stationLocations.ts`,
);
