// GENERATED by scripts/seed/build-pois.ts — do not edit by hand.
// Sources: data/coffee-ga-seed.csv, data/discovery/*.json, data/curation.json.
// Regenerate with: npm run seed:pois
import type { Poi } from "./pois";

export const generatedPoisByStation: Record<string, Poi[]> = {
  "north-avenue": [
    {
      "name": "Apotheos Coffee Midtown",
      "category": "coffee",
      "description": "Midtown Atlanta — about a 4-minute walk from the station.",
      "placeId": "ChIJPSqLR9AF9YgR0bYUfn3GZ6w",
      "rating": 4.6,
      "reviewCount": 127,
      "mapsUrl": "https://maps.google.com/?cid=12423116339413300945&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.22,
      "walkMinutes": 4
    },
    {
      "name": "Blue Donkey Craft Coffee 704",
      "category": "coffee",
      "description": "Georgia Tech — about a 10-minute walk from the station.",
      "placeId": "ChIJ2V1wo4kE9YgRzMIMR8PerT8",
      "rating": 4.2,
      "reviewCount": 232,
      "mapsUrl": "https://maps.google.com/?cid=4588568525652411084&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.52,
      "walkMinutes": 10
    },
    {
      "name": "Kaldi's Coffee",
      "category": "coffee",
      "description": "Georgia Tech — about a 11-minute walk from the station.",
      "placeId": "ChIJ86xzAygF9YgR33yPVHtXTLo",
      "rating": 3.1,
      "reviewCount": 71,
      "mapsUrl": "https://maps.google.com/?cid=13424200776495889631&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.55,
      "walkMinutes": 11
    },
    {
      "name": "Station 11 coffee",
      "category": "food",
      "description": "Midtown Atlanta — about a 1-minute walk from the station.",
      "placeId": "ChIJby6hxO4F9YgRf-HhIV0nebM",
      "rating": 4.9,
      "reviewCount": 31,
      "mapsUrl": "https://maps.google.com/?cid=12932411085924983167&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.04,
      "walkMinutes": 1
    }
  ],
  "midtown": [
    {
      "name": "Schāf Shop",
      "category": "coffee",
      "description": "Midtown Atlanta — about a 5-minute walk from the station.",
      "placeId": "ChIJ9UVFXcUF9YgRxN6gpd9qq5U",
      "rating": 4.9,
      "reviewCount": 116,
      "mapsUrl": "https://maps.google.com/?cid=10784831241457819332&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.25,
      "walkMinutes": 5
    },
    {
      "name": "Foxtail Coffee Co.",
      "category": "coffee",
      "description": "Midtown Atlanta — about a 7-minute walk from the station.",
      "placeId": "ChIJqxX9WPgF9YgR8j-sffrjhFU",
      "rating": 4.8,
      "reviewCount": 48,
      "mapsUrl": "https://maps.google.com/?cid=6162300855139450866&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.33,
      "walkMinutes": 7
    },
    {
      "name": "Larakin Wine & Coffee",
      "category": "coffee",
      "description": "Midtown Atlanta — about a 8-minute walk from the station.",
      "placeId": "ChIJ1d0S3aQF9YgRtCdQqVEno3I",
      "rating": 4.6,
      "reviewCount": 256,
      "mapsUrl": "https://maps.google.com/?cid=8260489373214058420&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.41,
      "walkMinutes": 8
    },
    {
      "name": "Dancing Goats Coffee Bar (Midtown)",
      "category": "coffee",
      "description": "Midtown Atlanta — about a 1-minute walk from the station.",
      "placeId": "ChIJsZEJ9mcE9YgRDTcnhgVcVaI",
      "rating": 4.5,
      "reviewCount": 1013,
      "mapsUrl": "https://maps.google.com/?cid=11697356785960040205&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.05,
      "walkMinutes": 1
    },
    {
      "name": "For Five Coffee Atlanta",
      "category": "coffee",
      "description": "Midtown Atlanta — about a 5-minute walk from the station.",
      "placeId": "ChIJAcvnz50F9YgRez_cjRE1v2g",
      "rating": 4.4,
      "reviewCount": 326,
      "mapsUrl": "https://maps.google.com/?cid=7547809850006978427&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.26,
      "walkMinutes": 5
    },
    {
      "name": "Daydreamer Coffee 859",
      "category": "coffee",
      "description": "Midtown Atlanta — about a 5-minute walk from the station.",
      "placeId": "ChIJT9zIslIF9YgRDkyUb3OQd_Q",
      "rating": 4.3,
      "reviewCount": 154,
      "mapsUrl": "https://maps.google.com/?cid=17615707292950613006&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.24,
      "walkMinutes": 5
    },
    {
      "name": "Spiller Park Coffee 999",
      "category": "coffee",
      "description": "Midtown Atlanta — about a 3-minute walk from the station.",
      "placeId": "ChIJYUb6404F9YgRFzKI2rs9B4U",
      "rating": 4.2,
      "reviewCount": 52,
      "mapsUrl": "https://maps.google.com/?cid=9585698208915927575&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.15,
      "walkMinutes": 3
    },
    {
      "name": "Cafe Lucia 205",
      "category": "coffee",
      "description": "Midtown Atlanta — about a 8-minute walk from the station.",
      "placeId": "ChIJtUV1VXwF9YgRpRcsib7qZnY",
      "rating": 4,
      "reviewCount": 452,
      "mapsUrl": "https://maps.google.com/?cid=8531764648166037413&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.39,
      "walkMinutes": 8
    },
    {
      "name": "Haraz Coffee House",
      "category": "treats",
      "description": "Midtown Atlanta — about a 3-minute walk from the station.",
      "placeId": "ChIJLyiPZGcE9YgR4YS29YMCvAU",
      "rating": 4.7,
      "reviewCount": 186,
      "mapsUrl": "https://maps.google.com/?cid=413208031597593825&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.17,
      "walkMinutes": 3
    },
    {
      "name": "Café Intermezzo (Midtown)",
      "category": "treats",
      "description": "Midtown Atlanta — about a 4-minute walk from the station.",
      "placeId": "ChIJicBn_aoF9YgRya-jWCHOmB0",
      "rating": 4.5,
      "reviewCount": 5943,
      "mapsUrl": "https://maps.google.com/?cid=2132681066176294857&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.21,
      "walkMinutes": 4
    }
  ],
  "civic-center": [
    {
      "name": "Aviator Coffee Company (Downtown)",
      "category": "coffee",
      "description": "Hotel District — about a 4-minute walk from the station.",
      "placeId": "ChIJjUpyD60F9YgR6d1vfT7V14o",
      "rating": 4.9,
      "reviewCount": 39,
      "mapsUrl": "https://maps.google.com/?cid=10004699561596018153&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.18,
      "walkMinutes": 4
    }
  ],
  "arts-center": [
    {
      "name": "Amistad Coffee",
      "category": "coffee",
      "description": "Midtown Atlanta — about a 1-minute walk from the station.",
      "placeId": "ChIJPyDtzLIF9YgRtJR4A8uG84o",
      "rating": 5,
      "reviewCount": 11,
      "mapsUrl": "https://maps.google.com/?cid=10012494603069461684&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.05,
      "walkMinutes": 1
    },
    {
      "name": "San Francisco Coffee Roasting Co. (Midtown)",
      "category": "coffee",
      "description": "Midtown Atlanta — about a 7-minute walk from the station.",
      "placeId": "ChIJ9c_pfAAF9YgRwtp-Psvxmnk",
      "rating": 4.8,
      "reviewCount": 9,
      "mapsUrl": "https://maps.google.com/?cid=8762581880231877314&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.34,
      "walkMinutes": 7
    },
    {
      "name": "Refuge Coffee Co. 1280",
      "category": "coffee",
      "description": "Midtown Atlanta — about a 3-minute walk from the station.",
      "placeId": "ChIJ2bYfNVAF9YgRZrq9lzwTmD8",
      "rating": 4.6,
      "reviewCount": 167,
      "mapsUrl": "https://maps.google.com/?cid=4582433771814238822&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.14,
      "walkMinutes": 3
    },
    {
      "name": "Land of a Thousand Hills Coffee 1140",
      "category": "coffee",
      "description": "Midtown Atlanta — about a 6-minute walk from the station.",
      "placeId": "ChIJ4aUwh0QF9YgR8uynEos2m9k",
      "rating": 4.6,
      "reviewCount": 138,
      "mapsUrl": "https://maps.google.com/?cid=15680186498561862898&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.28,
      "walkMinutes": 6
    },
    {
      "name": "Foxtail Coffee - Midtown Atlanta",
      "category": "coffee",
      "description": "Midtown Atlanta — about a 1-minute walk from the station.",
      "placeId": "ChIJdcJm4BkF9YgRDNpzeiYPJDE",
      "rating": 4.6,
      "reviewCount": 617,
      "mapsUrl": "https://maps.google.com/?cid=3540971864957639180&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.07,
      "walkMinutes": 1
    },
    {
      "name": "Pom Court",
      "category": "coffee",
      "description": "Midtown Atlanta — about a 2-minute walk from the station.",
      "placeId": "ChIJjSd39FoE9YgRoaYVtKqZAoM",
      "rating": 4.1,
      "reviewCount": 29,
      "mapsUrl": "https://maps.google.com/?cid=9440276727366788769&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.09,
      "walkMinutes": 2
    },
    {
      "name": "illy Atlantic Station",
      "category": "coffee",
      "description": "Atlantic Station — about a 12-minute walk from the station.",
      "placeId": "ChIJoSaYhVsF9YgRyp2NMaphkLQ",
      "rating": 4.1,
      "reviewCount": 278,
      "mapsUrl": "https://maps.google.com/?cid=13011006707077062090&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.61,
      "walkMinutes": 12
    },
    {
      "name": "White Windmill Bakery and Cafe 1331",
      "category": "treats",
      "description": "Midtown Atlanta — about a 3-minute walk from the station.",
      "placeId": "ChIJu3FxAgAF9YgRuBsw71LHqZw",
      "rating": 4.7,
      "reviewCount": 34,
      "mapsUrl": "https://maps.google.com/?cid=11288773099995012024&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.16,
      "walkMinutes": 3
    },
    {
      "name": "The Lazy Llama Coffeehouse - Atlantic Station",
      "category": "treats",
      "description": "Atlantic Station — about a 13-minute walk from the station.",
      "placeId": "ChIJJREkShEF9YgRLqXRjk5QsV8",
      "rating": 4.1,
      "reviewCount": 234,
      "mapsUrl": "https://maps.google.com/?cid=6895380802814715182&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.65,
      "walkMinutes": 13
    },
    {
      "name": "E+ROSE Wellness Cafe (Midtown)",
      "category": "food",
      "description": "Midtown Atlanta — about a 4-minute walk from the station.",
      "placeId": "ChIJu5ktRYEF9YgRwgG4D5Ks-vU",
      "rating": 4.5,
      "reviewCount": 86,
      "mapsUrl": "https://maps.google.com/?cid=17724669026798928322&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.21,
      "walkMinutes": 4
    },
    {
      "name": "Brasserie Margot",
      "category": "food",
      "description": "Midtown Atlanta — about a 5-minute walk from the station.",
      "placeId": "ChIJmUaKESQF9YgRMGn3jHIqTtY",
      "rating": 4.2,
      "reviewCount": 83,
      "mapsUrl": "https://maps.google.com/?cid=15442326843779672368&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.24,
      "walkMinutes": 5
    },
    {
      "name": "Dtox Juice",
      "category": "food",
      "description": "Midtown Atlanta — about a 4-minute walk from the station.",
      "placeId": "ChIJxVwE3NoF9YgRXQ8rVAAyxhY",
      "rating": 3.5,
      "reviewCount": 28,
      "mapsUrl": "https://maps.google.com/?cid=1641054091216621405&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.19,
      "walkMinutes": 4
    },
    {
      "name": "Saints + Council",
      "category": "drinks",
      "description": "Midtown Atlanta — about a 5-minute walk from the station.",
      "placeId": "ChIJ5YavCSYF9YgRLVrGI40hSu4",
      "rating": 4.5,
      "reviewCount": 1729,
      "mapsUrl": "https://maps.google.com/?cid=17170573419377744429&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.26,
      "walkMinutes": 5
    }
  ],
  "peachtree-center": [
    {
      "name": "Land Of A Thousand Hills Flatiron",
      "category": "coffee",
      "description": "Peachtree Center — about a 1-minute walk from the station.",
      "placeId": "ChIJb8zwAAAF9YgRMb2FRAUmufo",
      "rating": 4.8,
      "reviewCount": 30,
      "mapsUrl": "https://maps.google.com/?cid=18066513184239762737&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.05,
      "walkMinutes": 1
    },
    {
      "name": "Hansel & Gretel Bakery Cafe",
      "category": "treats",
      "description": "Fairlie-Poplar — about a 4-minute walk from the station.",
      "placeId": "ChIJeypDcwAD9YgRaPfLfcuVVsg",
      "rating": 4.2,
      "reviewCount": 276,
      "mapsUrl": "https://maps.google.com/?cid=14435890356804122472&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.21,
      "walkMinutes": 4
    },
    {
      "name": "Jittery Joe's Buckhead 308",
      "category": "treats",
      "description": "Peachtree Center — about a 2-minute walk from the station.",
      "placeId": "ChIJ2QRFdHgE9YgRcoD_81jMj9s",
      "rating": 4.1,
      "reviewCount": 83,
      "mapsUrl": "https://maps.google.com/?cid=15821088698398638194&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.08,
      "walkMinutes": 2
    },
    {
      "name": "Cafe Momo",
      "category": "food",
      "description": "Peachtree Center — about a 1-minute walk from the station.",
      "placeId": "ChIJUzEBW3gE9YgRzg_ZG-nzeAI",
      "rating": 3.8,
      "reviewCount": 128,
      "mapsUrl": "https://maps.google.com/?cid=178160367801274318&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.01,
      "walkMinutes": 1
    }
  ],
  "five-points": [
    {
      "name": "Dope Coffee @ Azalea",
      "category": "coffee",
      "description": "Five Points — about a 2-minute walk from the station.",
      "placeId": "ChIJYXtLxXQD9YgRdyBDCoQQ_1s",
      "rating": 4.9,
      "reviewCount": 64,
      "mapsUrl": "https://maps.google.com/?cid=6629035335806558327&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.12,
      "walkMinutes": 2
    },
    {
      "name": "Common Ground Coffee Shop",
      "category": "coffee",
      "description": "South Downtown — about a 4-minute walk from the station.",
      "placeId": "ChIJLbd3V34D9YgRPA6BJHtK9rU",
      "rating": 4.4,
      "reviewCount": 9,
      "mapsUrl": "https://maps.google.com/?cid=13111749257889648188&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.19,
      "walkMinutes": 4
    },
    {
      "name": "Café Lucia (Downtown)",
      "category": "coffee",
      "description": "Fairlie-Poplar — about a 3-minute walk from the station.",
      "placeId": "ChIJ2ad4IYcD9YgRtSYRsBsQ9dU",
      "rating": 4.3,
      "reviewCount": 681,
      "mapsUrl": "https://maps.google.com/?cid=15417246610476836533&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.16,
      "walkMinutes": 3
    }
  ],
  "king-memorial": [
    {
      "name": "Coffee Was Black (CWB)",
      "category": "coffee",
      "description": "Sweet Auburn — about a 8-minute walk from the station.",
      "placeId": "ChIJKbfyDnED9YgR6hw2_eysU1A",
      "rating": 4.8,
      "reviewCount": 75,
      "mapsUrl": "https://maps.google.com/?cid=5788160079961660650&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.4,
      "walkMinutes": 8
    },
    {
      "name": "Chrome Yellow Trading Co.",
      "category": "coffee",
      "description": "Old Fourth Ward — about a 8-minute walk from the station.",
      "placeId": "ChIJ-yzpL4wF9YgR4gopjocMzl4",
      "rating": 4.7,
      "reviewCount": 915,
      "mapsUrl": "Chrome Yellow",
      "distanceMiles": 0.39,
      "walkMinutes": 8
    },
    {
      "name": "Condesa Coffee (Old Fourth Ward)",
      "category": "coffee",
      "description": "Old Fourth Ward — about a 14-minute walk from the station.",
      "placeId": "ChIJLwAzPwoE9YgR6sHCuP90Y0g",
      "rating": 4.5,
      "reviewCount": 679,
      "mapsUrl": "Condesa Coffee",
      "distanceMiles": 0.72,
      "walkMinutes": 14
    }
  ],
  "east-point": [
    {
      "name": "Mocha Delites (East Point)",
      "category": "coffee",
      "description": "Jefferson Park — about a 4-minute walk from the station.",
      "placeId": "ChIJtfP20lId9YgRrra6oAxjg3M",
      "rating": 4,
      "reviewCount": 22,
      "mapsUrl": "https://maps.google.com/?cid=8323605442198156974&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.18,
      "walkMinutes": 4
    },
    {
      "name": "Kupcakerie",
      "category": "treats",
      "description": "Downtown — about a 2-minute walk from the station.",
      "placeId": "ChIJaX9DD1Md9YgRw6XpwH5irhc",
      "rating": 4.6,
      "reviewCount": 850,
      "mapsUrl": "https://maps.google.com/?cid=1706409605361935811&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.12,
      "walkMinutes": 2
    }
  ],
  "chamblee": [
    {
      "name": "Kin Coffee Co.",
      "category": "coffee",
      "description": "About a 6-minute walk from the station.",
      "placeId": "ChIJZbOXDAIJ9YgR0yLsz8v6_Cc",
      "rating": 4.8,
      "reviewCount": 167,
      "mapsUrl": "https://maps.google.com/?cid=2881453614883939027&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.31,
      "walkMinutes": 6
    },
    {
      "name": "Stellow Coffee & Floral",
      "category": "coffee",
      "description": "About a 7-minute walk from the station.",
      "placeId": "ChIJDZUG7dEb9YgR-zatKbSwJ4k",
      "rating": 4.8,
      "reviewCount": 119,
      "mapsUrl": "https://maps.google.com/?cid=9883062195127662331&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.35,
      "walkMinutes": 7
    },
    {
      "name": "Sidecar Coffee",
      "category": "coffee",
      "description": "About a 13-minute walk from the station.",
      "placeId": "ChIJW8plUZIJ9YgRaGT4cwbrcUk",
      "rating": 4.8,
      "reviewCount": 163,
      "mapsUrl": "https://maps.google.com/?cid=5292269450085033064&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.66,
      "walkMinutes": 13
    },
    {
      "name": "Choice Coffee Co",
      "category": "coffee",
      "description": "About a 11-minute walk from the station.",
      "placeId": "ChIJP1XppfkJ9YgRY-aqsiY5Ngg",
      "rating": 4.6,
      "reviewCount": 42,
      "mapsUrl": "https://maps.google.com/?cid=591723239414883939&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.53,
      "walkMinutes": 11
    },
    {
      "name": "D'Cuban Cafe chamblee",
      "category": "coffee",
      "description": "About a 15-minute walk from the station.",
      "placeId": "ChIJN_c2XWMJ9YgRqMGs4Lu3yB0",
      "rating": 4.6,
      "reviewCount": 713,
      "mapsUrl": "Google Maps",
      "distanceMiles": 0.73,
      "walkMinutes": 15
    },
    {
      "name": "Block & Drum",
      "category": "coffee",
      "description": "About a 8-minute walk from the station.",
      "placeId": "ChIJgRWLPi8J9YgR7R72Jmnlvk0",
      "rating": 4.4,
      "reviewCount": 132,
      "mapsUrl": "https://maps.google.com/?cid=5602167226283466477&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.39,
      "walkMinutes": 8
    },
    {
      "name": "Family Baking / Rolls Village",
      "category": "treats",
      "description": "About a 8-minute walk from the station.",
      "placeId": "ChIJl5raKhwJ9YgRiyGhAGi7NgU",
      "rating": 4.8,
      "reviewCount": 258,
      "mapsUrl": "https://maps.google.com/?cid=375693674293567883&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.39,
      "walkMinutes": 8
    },
    {
      "name": "Freddo Gelato & Coffee",
      "category": "treats",
      "description": "About a 10-minute walk from the station.",
      "placeId": "ChIJc0jUtN4J9YgRZdyy7vgGwwA",
      "rating": 4.7,
      "reviewCount": 106,
      "mapsUrl": "https://maps.google.com/?cid=54895286684933221&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.5,
      "walkMinutes": 10
    },
    {
      "name": "Laylo Cafe",
      "category": "treats",
      "description": "About a 8-minute walk from the station.",
      "placeId": "ChIJZ0LkzeMJ9YgRR1W1p_xhQYw",
      "rating": 4.4,
      "reviewCount": 156,
      "mapsUrl": "https://maps.google.com/?cid=10106466776569435463&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.38,
      "walkMinutes": 8
    },
    {
      "name": "The Bronx Bagel Buggy",
      "category": "treats",
      "description": "About a 13-minute walk from the station.",
      "placeId": "ChIJOZKp87EJ9YgR0KConhmt-xs",
      "rating": 4.3,
      "reviewCount": 478,
      "mapsUrl": "https://maps.google.com/?cid=2016395583726067920&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.65,
      "walkMinutes": 13
    },
    {
      "name": "LiveWire Coffee Pop-Up",
      "category": "food",
      "description": "About a 14-minute walk from the station.",
      "placeId": "ChIJQc_1cZJUlQkRGpdHOSduz9U",
      "rating": 5,
      "reviewCount": 24,
      "mapsUrl": "https://maps.google.com/?cid=15406653965001529114&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.7,
      "walkMinutes": 14
    }
  ],
  "college-park": [
    {
      "name": "C'est la Vie Cafe",
      "category": "coffee",
      "description": "About a 3-minute walk from the station.",
      "placeId": "ChIJG5KzeQDj9IgR9UjFZNLCpyw",
      "rating": 4.6,
      "reviewCount": 107,
      "mapsUrl": "https://maps.google.com/?cid=3217754667669080309&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.14,
      "walkMinutes": 3
    }
  ],
  "dunwoody": [
    {
      "name": "The Coffee House",
      "category": "coffee",
      "description": "Perimeter Center — about a 10-minute walk from the station.",
      "placeId": "ChIJP6agW34J9YgRcTCUkeP0zT8",
      "rating": 4.7,
      "reviewCount": 28,
      "mapsUrl": "https://maps.google.com/?cid=4597600052852306033&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.5,
      "walkMinutes": 10
    },
    {
      "name": "Just Love Coffee Cafe - Atlanta Perimeter",
      "category": "coffee",
      "description": "Perimeter Center — about a 8-minute walk from the station.",
      "placeId": "ChIJPUVLdTQJ9YgROfn7xob9Fn4",
      "rating": 4.6,
      "reviewCount": 752,
      "mapsUrl": "https://maps.google.com/?cid=9085728053572401465&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.41,
      "walkMinutes": 8
    },
    {
      "name": "Café Intermezzo (Sandy Springs)",
      "category": "treats",
      "description": "Perimeter Center — about a 11-minute walk from the station.",
      "placeId": "ChIJaY3FGl0J9YgRYPbZaAdV7T8",
      "rating": 4.3,
      "reviewCount": 2489,
      "mapsUrl": "https://maps.google.com/?cid=4606431484182132320&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.55,
      "walkMinutes": 11
    },
    {
      "name": "Cuddlefish",
      "category": "food",
      "description": "Perimeter Center — about a 4-minute walk from the station.",
      "placeId": "ChIJtdKgDAcJ9YgRRp3VA6b9tGU",
      "rating": 4.2,
      "reviewCount": 215,
      "mapsUrl": "https://maps.google.com/?cid=7328761383109369158&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.21,
      "walkMinutes": 4
    }
  ],
  "doraville": [
    {
      "name": "Java Saga",
      "category": "coffee",
      "description": "About a 14-minute walk from the station.",
      "placeId": "ChIJi6eAXMan9YgREkntvJIddhg",
      "rating": 4.8,
      "reviewCount": 453,
      "mapsUrl": "https://maps.google.com/?cid=1762628820234225938&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.7,
      "walkMinutes": 14
    },
    {
      "name": "Fluffy Fluffy Cafe",
      "category": "coffee",
      "description": "About a 12-minute walk from the station.",
      "placeId": "ChIJbzPOYjsJ9YgRQDB1OnAEh8g",
      "rating": 4.7,
      "reviewCount": 164,
      "mapsUrl": "https://maps.google.com/?cid=14449522809505132608&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.62,
      "walkMinutes": 12
    },
    {
      "name": "Common Coffee & Cocktails",
      "category": "coffee",
      "description": "About a 12-minute walk from the station.",
      "placeId": "ChIJBVfB3qSn9YgRuZY45kQOIy4",
      "rating": 4.3,
      "reviewCount": 120,
      "mapsUrl": "https://maps.google.com/?cid=3324516639012591289&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.62,
      "walkMinutes": 12
    },
    {
      "name": "Gula Indonesian Café",
      "category": "treats",
      "description": "About a 13-minute walk from the station.",
      "placeId": "ChIJeV_PHQAJ9YgRe62R4VYTAus",
      "rating": 4.9,
      "reviewCount": 109,
      "mapsUrl": "https://maps.google.com/?cid=16934118812739022203&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.66,
      "walkMinutes": 13
    },
    {
      "name": "Tom N Toms Atlanta",
      "category": "treats",
      "description": "About a 12-minute walk from the station.",
      "placeId": "ChIJa_I0FcoJ9YgR-JfyzTI-sL0",
      "rating": 4.8,
      "reviewCount": 138,
      "mapsUrl": "https://maps.google.com/?cid=13668493256993970168&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.6,
      "walkMinutes": 12
    },
    {
      "name": "Mozart Bakery & Cafe (Doraville)",
      "category": "treats",
      "description": "About a 9-minute walk from the station.",
      "placeId": "ChIJ1w1o388J9YgRJQo8_sYxWyk",
      "rating": 4.2,
      "reviewCount": 388,
      "mapsUrl": "https://maps.google.com/?cid=2980030309174348325&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.43,
      "walkMinutes": 9
    }
  ],
  "sandy-springs": [
    {
      "name": "The Bean Counter Northpark",
      "category": "coffee",
      "description": "Perimeter Center — about a 4-minute walk from the station.",
      "placeId": "ChIJxzOTb1UJ9YgR-xlY2P8f-R8",
      "rating": 5,
      "reviewCount": 13,
      "mapsUrl": "https://maps.google.com/?cid=2303907868083493371&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.19,
      "walkMinutes": 4
    },
    {
      "name": "Foxtail Coffee (Ashford Lane)",
      "category": "coffee",
      "description": "Perimeter Center — about a 10-minute walk from the station.",
      "placeId": "ChIJO73vPTgJ9YgRshzpN7C7w1w",
      "rating": 4.6,
      "reviewCount": 113,
      "mapsUrl": "https://maps.google.com/?cid=6684392637474610354&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.48,
      "walkMinutes": 10
    },
    {
      "name": "Bagel Boys Cafe (Sandy Springs)",
      "category": "treats",
      "description": "Perimeter Center — about a 4-minute walk from the station.",
      "placeId": "ChIJ3-qNe1MJ9YgRcgVaBvoNc8A",
      "rating": 4.3,
      "reviewCount": 580,
      "mapsUrl": "https://maps.google.com/?cid=13867443045103437170&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.2,
      "walkMinutes": 4
    }
  ],
  "vine-city": [
    {
      "name": "Friendship Market & Cafe (inside Signia Hilton)",
      "category": "food",
      "description": "Downtown Atlanta — about a 5-minute walk from the station.",
      "placeId": "ChIJiXvbmO0D9YgREFjVLLlpQKA",
      "rating": 4.5,
      "reviewCount": 3136,
      "mapsUrl": "https://maps.google.com/?cid=11547345688619997200&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.24,
      "walkMinutes": 5
    }
  ],
  "inman-park-reynoldstown": [
    {
      "name": "Harbor Coffee",
      "category": "coffee",
      "description": "Inman Park — about a 11-minute walk from the station.",
      "placeId": "ChIJJQJuVNgF9YgRtbcOd_tOr6k",
      "rating": 4.7,
      "reviewCount": 198,
      "mapsUrl": "https://maps.google.com/?cid=12227078355275397045&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.53,
      "walkMinutes": 11
    },
    {
      "name": "Bread & Butterfly",
      "category": "coffee",
      "description": "Inman Park — about a 9-minute walk from the station.",
      "placeId": "ChIJHwhNYAEE9YgRCs-R7L-_uWI",
      "rating": 4.5,
      "reviewCount": 1262,
      "mapsUrl": "Bread & Butterfly",
      "distanceMiles": 0.46,
      "walkMinutes": 9
    },
    {
      "name": "Inman Perk Coffee",
      "category": "coffee",
      "description": "Inman Park — about a 10-minute walk from the station.",
      "placeId": "ChIJlxVaAAQE9YgRmwcOR-WVc2o",
      "rating": 4,
      "reviewCount": 576,
      "mapsUrl": "https://maps.google.com/?cid=7670639402314237851&g_mp=Cidnb29nbGUubWFwcy5wbGFjZXMudjEuUGxhY2VzLlNlYXJjaFRleHQQAhgEIAA",
      "distanceMiles": 0.51,
      "walkMinutes": 10
    },
    {
      "name": "VOGA Italian Gelato",
      "category": "treats",
      "description": "Inman Park — about a 9-minute walk from the station.",
      "placeId": "ChIJY9mnWAEE9YgRZPxYBycoBNg",
      "rating": 4.7,
      "reviewCount": 917,
      "mapsUrl": "Voga Italian Gelato | Crepes | Coffee | Chocolate | Desserts",
      "distanceMiles": 0.47,
      "walkMinutes": 9
    }
  ]
};
