// GENERATED by scripts/seed/build-pois.ts — do not edit by hand.
// Placeholder until the first `npm run seed:pois -- --execute` run;
// see data/coffee-ga-seed.csv for the source data.
import type { Poi } from "./pois";

export const generatedPoisByStation: Record<string, Poi[]> = {};
