// GENERATED by scripts/seed/ingest-gtfs.ts — do not edit by hand.
// Source: MARTA GTFS static feed (stops.txt), parent rail stations.
// Regenerate with: npm run seed:gtfs -- path/to/stops.txt

export type StationLocation = {
  lat: number;
  lng: number;
  gtfsStopId: string;
  gtfsStopName: string;
};

export const stationLocations: Record<string, StationLocation> = {
  "north-springs": { lat: 33.94498, lng: -84.3572, gtfsStopId: "510028", gtfsStopName: "NORTH SPRINGS STATION" },
  "sandy-springs": { lat: 33.93174, lng: -84.35096, gtfsStopId: "510030", gtfsStopName: "SANDY SPRINGS STATION" },
  "dunwoody": { lat: 33.92124, lng: -84.34427, gtfsStopId: "510011", gtfsStopName: "DUNWOODY STATION" },
  "medical-center": { lat: 33.91072, lng: -84.35145, gtfsStopId: "510025", gtfsStopName: "MEDICAL CENTER STATION" },
  "buckhead": { lat: 33.84773, lng: -84.36766, gtfsStopId: "510036", gtfsStopName: "BUCKHEAD STATION" },
  "doraville": { lat: 33.90296, lng: -84.28026, gtfsStopId: "510010", gtfsStopName: "DORAVILLE STATION" },
  "chamblee": { lat: 33.88786, lng: -84.30566, gtfsStopId: "510006", gtfsStopName: "CHAMBLEE STATION" },
  "brookhaven-oglethorpe": { lat: 33.85999, lng: -84.3394, gtfsStopId: "510005", gtfsStopName: "BROOKHAVEN-OGLETHORPE STATION" },
  "lenox": { lat: 33.8454, lng: -84.35811, gtfsStopId: "510023", gtfsStopName: "LENOX STATION" },
  "lindbergh-center": { lat: 33.82291, lng: -84.36947, gtfsStopId: "510024", gtfsStopName: "LINDBERGH CENTER STATION" },
  "arts-center": { lat: 33.78918, lng: -84.38728, gtfsStopId: "510001", gtfsStopName: "ARTS CENTER STATION" },
  "midtown": { lat: 33.78107, lng: -84.38632, gtfsStopId: "510026", gtfsStopName: "MIDTOWN STATION" },
  "north-avenue": { lat: 33.77179, lng: -84.38709, gtfsStopId: "510027", gtfsStopName: "NORTH AVE STATION" },
  "civic-center": { lat: 33.76634, lng: -84.38749, gtfsStopId: "510007", gtfsStopName: "CIVIC CENTER STATION" },
  "peachtree-center": { lat: 33.759684, lng: -84.387598, gtfsStopId: "510040", gtfsStopName: "PEACHTREE CENTER STATION" },
  "five-points": { lat: 33.75387, lng: -84.39157, gtfsStopId: "510015", gtfsStopName: "FIVE POINTS STATION" },
  "garnett": { lat: 33.748544, lng: -84.395888, gtfsStopId: "510038", gtfsStopName: "GARNETT STATION" },
  "west-end": { lat: 33.73612, lng: -84.41364, gtfsStopId: "510033", gtfsStopName: "WEST END STATION" },
  "oakland-city": { lat: 33.71716, lng: -84.42507, gtfsStopId: "510029", gtfsStopName: "OAKLAND CITY STATION" },
  "lakewood-ft-mcpherson": { lat: 33.70042, lng: -84.42883, gtfsStopId: "510022", gtfsStopName: "LAKEWOOD-FT MCPHERSON STATION" },
  "east-point": { lat: 33.67753, lng: -84.4405, gtfsStopId: "510013", gtfsStopName: "EAST POINT STATION" },
  "college-park": { lat: 33.65159, lng: -84.44878, gtfsStopId: "510008", gtfsStopName: "COLLEGE PARK STATION" },
  "airport": { lat: 33.640806, lng: -84.446214, gtfsStopId: "510037", gtfsStopName: "AIRPORT STATION" },
  "bankhead": { lat: 33.77231, lng: -84.4289, gtfsStopId: "510004", gtfsStopName: "BANKHEAD STATION" },
  "hamilton-e-holmes": { lat: 33.75448, lng: -84.47003, gtfsStopId: "510017", gtfsStopName: "HAMILTON E HOLMES STATION" },
  "west-lake": { lat: 33.75327, lng: -84.4453, gtfsStopId: "510034", gtfsStopName: "WEST LAKE STATION" },
  "ashby": { lat: 33.75645, lng: -84.41728, gtfsStopId: "510002", gtfsStopName: "ASHBY STATION" },
  "vine-city": { lat: 33.75657, lng: -84.404, gtfsStopId: "510032", gtfsStopName: "VINE CITY STATION" },
  "sec-district": { lat: 33.75618, lng: -84.39725, gtfsStopId: "510039", gtfsStopName: "SEC DISTRICT STATION" },
  "georgia-state": { lat: 33.75007, lng: -84.38587, gtfsStopId: "510016", gtfsStopName: "GEORGIA STATE STATION" },
  "king-memorial": { lat: 33.7499, lng: -84.3758, gtfsStopId: "510021", gtfsStopName: "KING MEMORIAL STATION" },
  "inman-park-reynoldstown": { lat: 33.75753, lng: -84.35265, gtfsStopId: "510019", gtfsStopName: "INMAN PARK-REYNOLDSTOWN STATION" },
  "edgewood-candler-park": { lat: 33.76193, lng: -84.33962, gtfsStopId: "510014", gtfsStopName: "EDGEWOOD-CANDLER PARK STATION" },
  "east-lake": { lat: 33.76518, lng: -84.31315, gtfsStopId: "510012", gtfsStopName: "EAST LAKE STATION" },
  "decatur": { lat: 33.77468, lng: -84.29553, gtfsStopId: "510009", gtfsStopName: "DECATUR STATION" },
  "avondale": { lat: 33.77535, lng: -84.28191, gtfsStopId: "510003", gtfsStopName: "AVONDALE STATION" },
  "kensington": { lat: 33.77262, lng: -84.25192, gtfsStopId: "510020", gtfsStopName: "KENSINGTON STATION" },
  "indian-creek": { lat: 33.76982, lng: -84.22953, gtfsStopId: "510018", gtfsStopName: "INDIAN CREEK STATION" },
};
